### ISSUE TITLE
CSS broken

### ISSUE THREAD

**Issue by mcburton** [KeystoneDH/2021#1]
I enabled HTTPS as per KeystoneDH/keystonedh.github.io#1 

It looks like the CSS has borked. Might be the link to the style sheet is insecure?

**Comment by bulbil** [comment]
`site.github.url` jekyll-metadata issue -- added replace liquid filter workaround to `_include/head.html`

https://github.com/github/pages-gem/issues/238

**Comment by bulbil** [comment]
actually, just impatience -- build settings take a minute to update. only had to enable https on 2021 repo settings in addition to https on keystondh.github.io rep seetings.
